// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteNotification is an autogenerated mock type for the DeleteNotification type
type DeleteNotification struct {
	mock.Mock
}

// DeleteNotification provides a mock function with given fields: notificationID
func (_m *DeleteNotification) DeleteNotification(notificationID int64) error {
	ret := _m.Called(notificationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(notificationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeleteNotification creates a new instance of DeleteNotification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteNotification(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteNotification {
	mock := &DeleteNotification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
