// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GetNotificationStatus is an autogenerated mock type for the GetNotificationStatus type
type GetNotificationStatus struct {
	mock.Mock
}

// GetNotificationStatus provides a mock function with given fields: notificationID
func (_m *GetNotificationStatus) GetNotificationStatus(notificationID int64) (string, error) {
	ret := _m.Called(notificationID)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationStatus")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (string, error)); ok {
		return rf(notificationID)
	}
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(notificationID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(notificationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetNotificationStatus creates a new instance of GetNotificationStatus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetNotificationStatus(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetNotificationStatus {
	mock := &GetNotificationStatus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
