env: "local"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "your_password"
  dbname: "notifier"
  sslmode: "disable"

http_server:
  address: "localhost:8099"
  timeout: 4s
  idle_timeout: 60s

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_size: 10
  pool_timeout: 30s

rabbit:
  url: "amqp://guest:guest@localhost:5672/"

tg_token: "your_telegram_token"