// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CreateNotification is an autogenerated mock type for the CreateNotification type
type CreateNotification struct {
	mock.Mock
}

// CreateNotification provides a mock function with given fields: recipientID, dateStr, text
func (_m *CreateNotification) CreateNotification(recipientID int64, dateStr string, text string) (int64, error) {
	ret := _m.Called(recipientID, dateStr, text)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string, string) (int64, error)); ok {
		return rf(recipientID, dateStr, text)
	}
	if rf, ok := ret.Get(0).(func(int64, string, string) int64); ok {
		r0 = rf(recipientID, dateStr, text)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64, string, string) error); ok {
		r1 = rf(recipientID, dateStr, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCreateNotification creates a new instance of CreateNotification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateNotification(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateNotification {
	mock := &CreateNotification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
